// Canonical mapping for advertisement feature icons.
// Runtime assets live only in /public/icons/features.

const featureIconMap: Record<string, string> = {
  "پارکینگ": "parking.svg",
  "آسانسور": "evalator.svg",
  "حیاط": "yard.svg",
  "نقاشی": "paint.svg",
  "تراس": "terrace.svg",
  "کمد دیواری": "wardrobe.svg",
  "انباری": "warehouse.svg",
  "گاز رومیزی": "gas_stove.svg",
  "فر توکار": "oven.svg",
  "سرویس ایرانی": "toilet-iranian.svg",
  "سرویس فرنگی": "toilet-western.svg",
  "هود": "hood.svg",
  "دوربین مدار بسته": "cctv-camera.svg",
  "آیفون تصویری": "door-phone.svg",
  "روف گاردن": "roof-garden.svg",
  "کاغذ دیواری": "wallpaper.svg",
  "حمام مستر": "bathtub.svg",
  "درب برقی": "door-electronic.svg",
  "درب ضد سرقت": "door.svg",
  "نگهبانی": "shield.svg",
  "امتیاز برق": "power.svg",
  "سیستم هوشمند": "bms.svg",
  "امتیاز گاز": "gas.svg",
  "امتیاز آب": "water.svg",
  "امتیاز تلفن": "phone_2.svg",
  "دور دیوار": "wall.svg",
  "بنا کلنگی": "pick.svg",
  "چاه آب": "water-pump.svg",
  "جکوزی": "jacuzzi.svg",
  "سونا": "sauna.svg",
  "کافی شاپ": "coffee.svg",
  "فروشگاه": "shopping.svg",
  "رستوران": "restaurant.svg",
  "استخر": "pool.svg",
  "ترانسفر فرودگاهی": "transfer.svg",
  "سالن ماساژ": "masage.svg",
  "لابی": "lobby.svg",
  "سالن ورزشی": "gym.svg",
  "سالن اجتماعات": "meeting-room.svg",
  "صرافی": "exchange.svg",
  "سینما": "camera.svg",
  "نقاش": "painter.svg",
  "زمین بازی": "playground.svg",
  "برق تک فاز": "single-phase-power.svg",
  "برق سه فاز": "three-phase-power.svg",
  "سیستم صوتی": "sound-system.svg",
  "ماشین لباسشویی": "washing-machine.svg",
  "ماشین ظرفشویی": "dishwasher.svg",
  "دستگاه قهوه ساز": "coffee-maker.svg",
  "سیستم تهویه مطبوع": "air-conditioning-system.svg",
  "اتو": "iron.svg",
  "سشوار": "hair-dryer.svg",
  "ملحفه و حوله تمیز": "clean-linens-towels.svg",
  "یخچال": "refrigerator.svg",
  "میزناهار خوری": "dining-table.svg",
  "ظروف و لوازم پذیرایی": "tableware.svg",
  "پک بهداشتی": "hygiene-kit.svg",
  "مبلمان": "furniture.svg",
  "تخت خواب": "bed.svg",
  "فضا کار": "workspace.svg",
  "ویدئو پرژکتور": "video-projector.svg",
  "اینترنت پر سرعت": "high-speed-internet.svg",
  "فضا سبز/باغ": "green-space-garden.svg",
  "آلاچیق": "gazebo.svg",
  "باربیکیو": "barbecue.svg",
  "اتاق مستر": "master-room.svg",
  "کامپیوتر/لبتاب": "computer-laptop.svg",
  "دستگاه فکس": "fax.svg",
  "پذیرایی": "reception.svg",
  "میزوصندلی اداری": "office-desk-chair.svg",
  "پرینتر/اسکنر": "printer-scanner.svg",
  "تخته وایت برد": "whiteboard.svg",
  "اتاق استراحت": "break-room.svg",
  "قفسه وفایلینگ": "shelving-filing.svg",
  "دستگاه کپی": "copier.svg",
  "تلویزیون": "television.svg",
  "مانیتور": "monitor.svg",
  "تلفن کنفرانس": "conference-phone.svg",
  "فضای بیرونی": "outdoor-space.svg",
  "کولر گازی": "coolerGazi.svg",
  "کولر آبی": "coolerAbi.svg",
  "پکیج": "package.svg",
  "آبگرمکن": "abGarmKon.svg",
  "آبگرم کن": "abGarmKon.svg",
  "بخاری": "heater.svg",
  "شوفاژ": "shoofaj.svg",
  "کافی\u200cشاپ": "coffee.svg",
  "گازرومیزی": "gas_stove.svg",
  "فرتوکار": "oven.svg",
  "امتیازآب": "water.svg",
  "دور دیوار/حصار": "wall.svg",
  "دوربین امنیتی": "cctv-camera.svg",
  "دوربین": "cctv-camera.svg",
  "استخر آب گرم": "pool.svg",
  "استخر روباز": "pool.svg",
  "استخرروباز": "pool.svg",
  "استخر سرپوشیده": "pool.svg",
  "استخر پوشیده": "pool.svg",
  "فضا بیرونی": "outdoor-space.svg",
  "فضای کار": "workspace.svg",
  "با لوازم و مبله شده": "furniture.svg",
  "سرویس خواب": "bed.svg",
  "چیلر": "chiller.svg",
  "داکت اسپلیت": "duct-split.svg",
  "داکت اسپیلت": "duct-split.svg",
  "فن کوئل": "fan-coil.svg",
  "فن‌کوئل": "fan-coil.svg",
  "گرمایش ازکف": "floor-heating.svg",
  "گرمایش از کف": "floor-heating.svg",
  "شومینه": "fireplace.svg",
  "موتورخانه": "central-boiler.svg",
};

function normalizeFeatureLabel(value: string) {
  return value.trim().replace(/\s+/g, " ");
}

export function getFeatureIconSrc(feature: string) {
  const iconName = featureIconMap[normalizeFeatureLabel(feature)];
  return iconName ? `/icons/features/${iconName}` : null;
}
