import type { AdvertisementItem } from "../../services/advertisement.service";

export const singleAdMockData: AdvertisementItem = {
  id: "000000000000000000000601",
  title: "فروش کامل واحد اداری در مشهد",
  price: 11800000000,
  image: "/public/demo/real-estate-placeholder.jpg",
  images: ["/public/demo/real-estate-placeholder.jpg"],
  features: [
    { label: "form_code", value: "sale-office" },
    { label: "neighborhood_id", value: "000000000000000000000301" },
    { label: "area", value: 110 },
    { label: "price", value: 11800000000 },
    { label: "building_age", value: "نوساز" },
    { label: "rooms", value: "2" },
    { label: "floor", value: "1" },
    { label: "has_document", value: true },
    { label: "renovated", value: true },
    { label: "furnished", value: true },
    { label: "has_loan", value: true },
    { label: "suitable_for", value: ["وکلا", "شرکت ها", "مطب"] },
    { label: "document_type", value: "ملکی" },
    { label: "heating_cooling", value: ["کولر گازی", "پکیج"] },
    { label: "unit_direction", value: "شمالی" },
    { label: "land_position", value: "۳ نبش" },
    { label: "total_floors", value: 4 },
    { label: "floor_material", value: "سرامیک" },
    { label: "facade_material", value: "سنگ" },
    { label: "cabinet_material", value: "ام دی اف" },
    { label: "loan_amount", value: 1500000000 },
    { label: "loan_installment", value: 500000000 },
    { label: "has_loan", value: false },
    { label: "exchange_with", value: [] },
    {
      label: "facilities",
      value: [
        "آسانسور",
        "رستوران",
        "کافی‌شاپ",
        "لابی",
        "استخر",
        "سالن ماساژ",
        "سونا",
        "جکوزی",
        "فروشگاه",
        "سالن ورزشی",
        "دوربین مدار بسته",
        "امتیاز برق",
        "امتیاز گاز",
        "امتیاز آب",
        "نگهبانی",
        "دور دیوار",
        "چاه آب",
      ],
    },
    {
      label: "exchange_with",
      value: ["ویلا", "خودرو", "آپارتمان", "خانه ویلایی", "زمین"],
    },
    { label: "advertiser_type", value: "مشاور املاک" },
    { label: "published_at", value: "امروز" },
    { label: "is_special", value: false },
    { label: "has_image", value: true },
    { label: "has_video", value: false },
  ],
  short_description:
    "فروش کامل واحد اداری در مشهد با تمام فیلدهای فرم برای تست کامل فرانت‌اند.",
  label: "فروش کامل واحد اداری در مشهد",
  published_hours_ago: 23,
  created_at: "2026-06-15T08:16:11.508Z",
  lat: 36.2972,
  lng: 59.6067,
  _id: "000000000000000000000601",
  category_id: "000000000000000000000235",
  neighborhood_id: "000000000000000000000301",
  user_id: null,
  status: 3,
  description:
    "فروش کامل واحد اداری در مشهد با تمام فیلدهای فرم برای تست کامل فرانت‌اند.",
  track_code: 930001,
  contact_type: ["phone"],
  owner_phone: "09152000001",
  owner_type: "owner",
  virtual_tour_link: null,
  payments: [],
  confirm_date: "2026-06-15T08:16:11.508Z",
  sort_date: "2026-06-15T07:16:11.508Z",
  updated_at: "2026-06-15T12:28:40.092Z",
};

export const mockAdIds = new Set(["000000000000000000000601", "601", "930001"]);

