export const typography = {
  displayLg: "text-[57px] font-normal leading-[64px]",
  displayMd: "text-[45px] font-normal leading-[52px]",
  displaySm: "text-[36px] font-normal leading-[44px]",
  headlineLg: "text-[32px] font-normal leading-[40px]",
  headlineMd: "text-2xl font-normal leading-[36px]",
  headlineSm: "text-2xl font-normal leading-[32px]",
  titleLg: "text-[22px] font-semibold leading-[28px]",
  titleMd: "text-base font-semibold leading-[24px]",
  titleSm: "text-sm font-semibold leading-[20px]",
  labelLg: "text-base font-medium leading-[24px]",
  labelMd: "text-sm font-medium leading-[20px]",
  labelSm: "text-xs font-medium leading-[16px]",
  bodyLg: "text-base font-normal leading-[24px]",
  bodyMd: "text-sm font-normal leading-[20px]",
  bodySm: "text-xs font-normal leading-[16px]",
  appBarTitle: "text-base font-semibold leading-[24px]",
  button: "text-base font-medium leading-[24px]",
  chip: "text-sm font-medium leading-[20px]",
  navLabel: "text-xs font-medium leading-[16px]",
  fieldInput: "text-base font-normal leading-[24px]",
  fieldLabel: "text-xs font-normal leading-[20px]",
  helper: "text-xs font-normal leading-[20px]",
} as const;
