export const typography = {
  displayLg: "text-[57px] font-normal leading-[66px]",
  displayMd: "text-[45px] font-normal leading-[54px]",
  displaySm: "text-[36px] font-normal leading-[46px]",
  headlineLg: "text-[32px] font-normal leading-[42px]",
  headlineMd: "text-2xl font-normal leading-[38px]",
  headlineSm: "text-2xl font-normal leading-9",
  titleLg: "text-[22px] font-semibold leading-8",
  titleMd: "text-base font-semibold leading-6",
  titleSm: "text-sm font-semibold leading-[22px]",
  labelLg: "text-base font-medium leading-[22px]",
  labelMd: "text-sm font-medium leading-[18px]",
  labelSm: "text-xs font-medium leading-[18px]",
  bodyLg: "text-base font-normal leading-7",
  bodyMd: "text-sm font-normal leading-[22px]",
  bodySm: "text-xs font-normal leading-[18px]",
  appBarTitle: "text-base font-semibold leading-6",
  button: "text-base font-medium leading-6",
  chip: "text-sm font-medium leading-5",
  navLabel: "text-xs font-medium leading-4",
  fieldInput: "text-base font-normal leading-6",
  fieldLabel: "text-xs font-normal leading-5",
  helper: "text-xs font-normal leading-5",
} as const;
