export const propertyRequestFilterLabels: Record<string, string> = {
  area_max: "حداکثر متراژ",
  area_min: "حداقل متراژ",
  building_age: "سن بنا",
  category_id: "دسته‌بندی",
  city_id: "شهر",
  exchange_with: "معاوضه با",
  floor: "طبقه",
  form_code: "نوع معامله",
  from_code: "نوع معامله",
  has_image: "دارای تصویر",
  has_video: "دارای ویدئو",
  is_special: "آگهی ویژه",
  neighborhood_id: "محله",
  neighborhoods: "محله",
  price_max: "حداکثر قیمت",
  price_min: "حداقل قیمت",
  published_at: "زمان انتشار",
  query: "عبارت جستجو",
  q: "عبارت جستجو",
  qsearch: "عبارت جستجو",
  rooms: "تعداد اتاق",
};

export const propertyRequestCategoryLabels: Record<string, string> = {
  apartment: "آپارتمان",
  "villa-house": "خانه و ویلا",
  "garden-villa": "ویلا، باغ",
  land: "زمین، ملک کلنگی",
  office: "اداری",
  "commercial-unit": "تجاری",
  commercial: "تجاری",
  warehouse: "انبار، سوله",
  "hotel-apartment": "هتل، اقامتگاه",
  "factory-workshop": "صنعتی، کارگاه",
  "daily-apartment-suite": "آپارتمان، سوئیت",
  "daily-garden-villa": "ویلا، باغ",
  "daily-hotel-apartment": "هتل، اقامتگاه",
  "daily-workspace": "دفترکار، غرفه",
  "project-presale": "پیش فروش",
  "project-partnership": "مشارکت",
  residential: "مسکونی",
  store: "مغازه",
};

export const formCodeLabels: Record<string, string> = {
  "rent-apartment": "اجاره آپارتمان",
  "sale-apartment": "فروش آپارتمان",
  "sale-garden-villa": "فروش باغ ویلا",
  "rent-garden-villa": "اجاره باغ ویلا",
  "rent-villa": "اجاره ویلا",
  "sale-villa": "فروش ویلا",
  "sale-villa-house": "فروش خانه و ویلا",
  "rent-villa-house": "اجاره خانه و ویلا",
  "sale-land": "فروش زمین و کلنگی",
  "rent-land": "اجاره زمین",
  "sale-office": "فروش اداری",
  "rent-office": "اجاره اداری",
  "sale-commercial": "فروش تجاری",
  "rent-commercial": "اجاره تجاری",
  "sale-commercial-unit": "فروش تجاری",
  "rent-commercial-unit": "اجاره تجاری",
  "rent-daily": "اجاره روزانه",
  sale: "فروش",
  rent: "اجاره",
  daily: "اجاره روزانه",
  presale: "پیش‌فروش",
  partnership: "مشارکت",
  exchange: "معاوضه",
};

export const roomLabels: Record<string, string> = {
  "0": "بدون اتاق",
  "1": "یک خوابه",
  "2": "دو خوابه",
  "3": "سه خوابه",
  "4": "چهار خوابه",
  "5": "پنج خوابه",
  "2_3": "دو یا سه خوابه",
};

export const cityLabels: Record<string, string> = {
  isfahan: "اصفهان",
  mashhad: "مشهد",
  shiraz: "شیراز",
  tehran: "تهران",
};
