import type { AdCardData } from "../../advertisements/components/AdCard";

export const defaultRecentAds: AdCardData[] = [
  {
    id: "ad-1",
    title: "۱۴۰متر*تکواحدی ابتدای صیاد*فول امکانات",
    agency: "املاک بزرگ نیاوران",
    status: "تایید شده",
    statusBadgeClassName: "bg-tertiary/10 text-tertiary",
    imageCount: "۵",
    priceLabelPrimary: "",
    pricePrimary: "۷٫۶۵۰ میلیارد تومان",
    priceLabelSecondary: "",
    priceSecondary: "",
    area: "۱۴۰ متر",
    rooms: "۳ خواب",
    year: "۱۳۹۵",
    timeAndLocation: "۱ ساعت پیش در صیاد شیرازی",
    imageClassName: "",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80",
    badges: ["فوری", "ویژه"],
  },
  {
    id: "ad-2",
    title: "آپارتمان ۱۲۰ متری نوساز کلید نخورده سعادت‌آباد",
    agency: "املاک کاخ",
    status: "تایید شده",
    statusBadgeClassName: "bg-tertiary/10 text-tertiary",
    imageCount: "۸",
    priceLabelPrimary: "",
    pricePrimary: "۱۵٫۲۰۰ میلیارد تومان",
    priceLabelSecondary: "",
    priceSecondary: "",
    area: "۱۲۰ متر",
    rooms: "۲ خواب",
    year: "۱۴۰۲",
    timeAndLocation: "۳ ساعت پیش در سعادت‌آباد",
    imageClassName: "",
    imageUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=80",
    badges: ["ویژه"],
  },
  {
    id: "ad-3",
    title: "ویلای دوبلکس ۳۵۰ متری شهرکی لواسان",
    agency: "املاک رویال",
    status: "تایید شده",
    statusBadgeClassName: "bg-tertiary/10 text-tertiary",
    imageCount: "۱۲",
    priceLabelPrimary: "",
    pricePrimary: "۳۸٫۰۰۰ میلیارد تومان",
    priceLabelSecondary: "",
    priceSecondary: "",
    area: "۳۵۰ متر",
    rooms: "۴ خواب",
    year: "۱۳۹۸",
    timeAndLocation: "دیروز در لواسان",
    imageClassName: "",
    imageUrl: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=80",
    badges: ["فوری"],
  },
  {
    id: "ad-4",
    title: "پنت‌هاوس ۲۸۰ متری دید ابدی زعفرانیه",
    agency: "املاک پارس",
    status: "تایید شده",
    statusBadgeClassName: "bg-tertiary/10 text-tertiary",
    imageCount: "۱۰",
    priceLabelPrimary: "",
    pricePrimary: "۵۵٫۰۰۰ میلیارد تومان",
    priceLabelSecondary: "",
    priceSecondary: "",
    area: "۲۸۰ متر",
    rooms: "۴ خواب",
    year: "۱۴۰۱",
    timeAndLocation: "۲ روز پیش در زعفرانیه",
    imageClassName: "",
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80",
    badges: ["ویژه"],
  },
  {
    id: "ad-5",
    title: "آپارتمان ۹۵ متری خوش‌نقشه نورگیر جنت‌آباد",
    agency: "املاک آریا",
    status: "تایید شده",
    statusBadgeClassName: "bg-tertiary/10 text-tertiary",
    imageCount: "۴",
    priceLabelPrimary: "",
    pricePrimary: "۶٫۸۰۰ میلیارد تومان",
    priceLabelSecondary: "",
    priceSecondary: "",
    area: "۹۵ متر",
    rooms: "۲ خواب",
    year: "۱۳۹۲",
    timeAndLocation: "۳ روز پیش در جنت‌آباد",
    imageClassName: "",
    imageUrl: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&auto=format&fit=crop&q=80",
    badges: [],
  },
];
