import type { ViewAdLeadItem } from "./ViewAdLeadCard";

export const MOCK_VIEW_AD_LEADS: ViewAdLeadItem[] = [
  {
    id: "lead-1",
    name: "ناصر اشرفی",
    phone: "09155214062",
    avatarUrl: "/mock/lead-avatar-sample.jpg",
    status: "بازدید",
    statusType: "success",
    date: "پنجشنبه ۳۱ تیر",
    time: "۱۸:۰۰",
    chatCount: 5,
    callCount: 2,
    detailsUrl: "/account/dashboard/lead-followup",
  },
  {
    id: "lead-2",
    name: "ناصر اشرفی",
    phone: "09155214062",
    avatarUrl: "/mock/lead-avatar-sample.jpg",
    status: "بازدید",
    statusType: "success",
    date: "پنجشنبه ۳۱ تیر",
    time: "۱۸:۰۰",
    chatCount: 5,
    callCount: 2,
    detailsUrl: "/account/dashboard/lead-followup",
  },
  {
    id: "lead-3",
    name: "ناصر اشرفی",
    phone: "09155214062",
    avatarUrl: "/mock/lead-avatar-sample.jpg",
    status: "بازدید",
    statusType: "success",
    date: "پنجشنبه ۳۱ تیر",
    time: "۱۸:۰۰",
    chatCount: 5,
    callCount: 2,
    detailsUrl: "/account/dashboard/lead-followup",
  },
  {
    id: "lead-4",
    name: "سارا محمدی",
    phone: "09123456789",
    status: "جدید",
    statusType: "info",
    date: "جمعه ۱ مرداد",
    time: "۱۰:۳۰",
    chatCount: 1,
    callCount: 0,
    detailsUrl: "/account/dashboard/lead-followup",
  },
  {
    id: "lead-5",
    name: "امیرحسین رضایی",
    phone: "09351234567",
    status: "پیگیری",
    statusType: "warning",
    date: "شنبه ۲ مرداد",
    time: "۱۵:۰۰",
    chatCount: 3,
    callCount: 1,
    detailsUrl: "/account/dashboard/lead-followup",
  },
  {
    id: "lead-6",
    name: "مهدی علیزاده",
    phone: "09191234567",
    status: "انصراف",
    statusType: "warning",
    date: "یکشنبه ۳ مرداد",
    time: "۱۴:۲۰",
    chatCount: 2,
    callCount: 1,
    detailsUrl: "/account/dashboard/lead-followup",
  },
];
