export type TransactionLabel = "فروش" | "اجاره" | "پروژه";

export type NewAdScenario = {
  transaction: "sale" | "rent" | "project";
  transactionLabel: TransactionLabel;
  section: string;
  category: string;
  categoryLabel: string;
  formCode: string;
  expectedFields: string[];
};

export const newAdScenarios: NewAdScenario[] = [
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "مسکونی",
    category: "apartment",
    categoryLabel: "آپارتمان",
    formCode: "sale-apartment",
    expectedFields: ["متراژ آپارتمان *", "طبقه *", "تعداد اتاق ها *", "سن ساخت *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "مسکونی",
    category: "land",
    categoryLabel: "زمین",
    formCode: "sale-land",
    expectedFields: ["متراژ زمین *", "نوع کاربری *", "موقعیت زمین *", "نوع سند *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "مسکونی",
    category: "villa-house",
    categoryLabel: "خانه ویلایی",
    formCode: "sale-villa-house",
    expectedFields: ["متراژ زمین *", "زیربنا *", "تعداد اتاق ها *", "سن ساخت *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "مسکونی",
    category: "garden-villa",
    categoryLabel: "باغ، ویلا",
    formCode: "sale-garden-villa",
    expectedFields: ["متراژ زمین *", "زیربنا *", "تعداد اتاق ها *", "سن ساخت *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "office",
    categoryLabel: "واحد اداری",
    formCode: "sale-office",
    expectedFields: ["متراژ *", "مناسب برای *", "تعداد اتاق ها *", "نوع سند *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "commercial-unit",
    categoryLabel: "واحد تجاری",
    formCode: "sale-commercial",
    expectedFields: ["متراژ *", "مناسب برای *", "نوع سند *", "سن ساخت *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "warehouse",
    categoryLabel: "انبار، سوله",
    formCode: "sale-warehouse",
    expectedFields: ["متراژ زمین *", "زیربنا *", "موقعیت زمین *", "مناسب برای *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "hotel-apartment",
    categoryLabel: "هتل، هتل آپارتمان",
    formCode: "sale-hotel",
    expectedFields: ["رتبه‌بندی هتل *", "متراژ *", "نوع سند *", "موقعیت زمین *", "سن ساخت *", "قیمت *"],
  },
  {
    transaction: "sale",
    transactionLabel: "فروش",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "factory-workshop",
    categoryLabel: "کارخانه، کارگاه",
    formCode: "sale-factory",
    expectedFields: ["متراژ زمین *", "زیربنا *", "نوع سند *", "قیمت *"],
  },

  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "مسکونی",
    category: "apartment",
    categoryLabel: "آپارتمان",
    formCode: "rent-apartment",
    expectedFields: ["متراژ آپارتمان *", "طبقه *", "تعداد اتاق ها *", "سن ساخت *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "مسکونی",
    category: "villa-house",
    categoryLabel: "خانه ویلایی",
    formCode: "rent-villa-house",
    expectedFields: ["متراژ زمین *", "زیربنا *", "تعداد اتاق ها *", "سن ساخت *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "مسکونی",
    category: "garden-villa",
    categoryLabel: "باغ، ویلا",
    formCode: "rent-garden-villa",
    expectedFields: ["متراژ زمین *", "زیربنا *", "تعداد اتاق ها *", "سن ساخت *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "روزانه",
    category: "daily-apartment-suite",
    categoryLabel: "آپارتمان، سوئیت",
    formCode: "daily-apartment-suite",
    expectedFields: ["متراژ *", "تعداد اتاق *", "ظرفیت استاندارد *", "تعداد نفرات اضافه *", "حداقل قیمت *", "حداکثر قیمت *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "روزانه",
    category: "daily-garden-villa",
    categoryLabel: "باغ، ویلا",
    formCode: "daily-garden-villa",
    expectedFields: ["متراژ *", "تعداد اتاق *", "ظرفیت استاندارد *", "تعداد نفرات اضافه *", "حداقل قیمت *", "حداکثر قیمت *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "روزانه",
    category: "daily-hotel-apartment",
    categoryLabel: "هتل، هتل آپارتمان",
    formCode: "daily-hotel",
    expectedFields: ["رتبه‌بندی هتل *", "حداقل قیمت *", "حداکثر قیمت *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "روزانه",
    category: "daily-workspace",
    categoryLabel: "دفاتر کار، غرفه، نمایشگاه",
    formCode: "daily-office-booth",
    expectedFields: ["متراژ *", "تعداد اتاق *", "ظرفیت استاندارد *", "تعداد نفرات اضافه *", "حداقل قیمت *", "حداکثر قیمت *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "office",
    categoryLabel: "واحد اداری",
    formCode: "rent-office",
    expectedFields: ["متراژ *", "طبقه آپارتمان *", "تعداد اتاق ها *", "سن ساخت *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "commercial-unit",
    categoryLabel: "واحد تجاری",
    formCode: "rent-commercial",
    expectedFields: ["متراژ *", "طبقه آپارتمان *", "تعداد اتاق ها *", "سن ساخت *", "مناسب برای *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "warehouse",
    categoryLabel: "انبار، سوله",
    formCode: "rent-warehouse",
    expectedFields: ["متراژ زمین *", "زیربنا *", "موقعیت زمین *", "ارتفاع سقف *", "مناسب برای *", "مجوز تجاری *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "hotel-apartment",
    categoryLabel: "هتل، هتل آپارتمان",
    formCode: "rent-hotel",
    expectedFields: ["متراژ زمین *", "زیربنا *", "موقعیت زمین *", "سن ساخت *", "رهن *", "اجاره *"],
  },
  {
    transaction: "rent",
    transactionLabel: "اجاره",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "factory-workshop",
    categoryLabel: "کارخانه، کارگاه",
    formCode: "rent-factory-workshop",
    expectedFields: ["متراژ زمین *", "زیربنا *", "رهن *", "اجاره *"],
  },

  {
    transaction: "project",
    transactionLabel: "پروژه",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "project-presale",
    categoryLabel: "پیش فروش، فروش پروژه",
    formCode: "presale-special",
    expectedFields: ["تعداد کل طبقات *", "تعداد کل واحدها *", "وضعیت پروژه *", "تاریخ تحویل *", "حداقل قیمت *", "حداکثر قیمت *"],
  },
  {
    transaction: "project",
    transactionLabel: "پروژه",
    section: "اداری، تجاری، صنعتی، اقامتی",
    category: "project-partnership",
    categoryLabel: "مشارکت",
    formCode: "partnership",
    expectedFields: ["نوع مشارکت *", "متراژ زمین *", "مجوز ساخت *", "نوع سند *", "سهم سازنده به درصد *"],
  },
];

export const expectedMoreFeatureFieldsByScenario: Record<string, string[]> = {
  "sale:apartment": [
    "تعداد طبقات آپارتمان",
    "تعداد واحد در طبقه",
    "جهت ساختمان",
    "موقعیت واحد",
    "نوع سند",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "sale:land": ["عرض زمین", "عرض خیابان", "تراکم", "مجوز ساخت"],
  "sale:villa-house": [
    "موقعیت زمین",
    "تیپ ویلا",
    "نوع سند",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "sale:garden-villa": [
    "تیپ ویلا",
    "نوع سند",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "sale:office": [
    "طبقه",
    "مجوز تجاری",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "sale:commercial-unit": ["تعداد اتاق", "مجوز تجاری", "طبقه", "تعداد کل طبقات"],
  "sale:warehouse": ["عرض زمین", "ارتفاع سقف", "نوع سند", "مجوز تجاری"],
  "sale:hotel-apartment": [
    "تعداد طبقات",
    "تعداد اتاق یک تخته",
    "تعداد اتاق دو تخته",
    "تعداد سوییت‌ها",
    "بازسازی شده",
    "مبله با لوازم",
  ],
  "sale:factory-workshop": [],

  "rent:apartment": [
    "تعداد طبقات آپارتمان",
    "جهت ساختمان",
    "موقعیت واحد",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:villa-house": [
    "موقعیت زمین",
    "تیپ ویلا",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:garden-villa": [
    "تیپ ویلا",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:daily-apartment-suite": [
    "تعداد طبقات آپارتمان",
    "جهت ساختمان",
    "موقعیت واحد",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:daily-garden-villa": [
    "تیپ ویلا",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:daily-hotel-apartment": [],
  "rent:daily-workspace": [
    "طبقه",
    "مجوز تجاری",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:office": [
    "طبقه",
    "مجوز تجاری",
    "بازسازی شده",
    "مبله با لوازم",
    "جنس نما",
    "جنس کف",
    "جنس کابینت",
  ],
  "rent:commercial-unit": [],
  "rent:warehouse": [],
  "rent:hotel-apartment": [
    "تعداد طبقات",
    "تعداد اتاق یک تخته",
    "تعداد اتاق دو تخته",
    "تعداد سوییت‌ها",
    "بازسازی شده",
    "مبله با لوازم",
  ],
  "rent:factory-workshop": [],

  "project:project-presale": [],
  "project:project-partnership": [],
};

export function expectedMoreFeatureFields(scenario: NewAdScenario) {
  return expectedMoreFeatureFieldsByScenario[`${scenario.transaction}:${scenario.category}`] ?? [];
}
